- sc.asd
- server.lisp
- ugens/extras/envfollow.lisp
- ugens/poll.lisp
These changes add the Poll and EnvFollow UGens. EnvFollow is part of sc3-plugins, not the main supercollider distribution, so some users may not have it.
I also added an OSC responder so that Poll's output would be printed in the REPL. However it seems like in some cases Poll will be removed by the compiler if it's not part of the audio output.
> Add EnvFollow and Poll UGens

- util.lisp
It looks like SBCL isn't printing stdout from the server when #'sc::run-program :output is t. This is a simple fix to make SBCL post scsynth's output in the REPL.
> sbcl: server STDOUT to *standard-output* when run-program output = t

- synthdef.lisp
This change prevents variables that have the same name as functions from being converted to the name of the function.
Previous behavior:
```lisp
> (sc::convert-code '(exp exp))
(SC::EXP~ SC::EXP~)
```
New/corrected behavior:
```lisp
> (sc::convert-code '(exp exp))
(SC::EXP~ EXP)
```
> only convert atoms at the head of lists.

- ugens/filter.lisp
Since detect-silence has possible side effects (i.e. freeing the synth) it should not be a pure-ugen. This commit fixes that.
> detect-silence may have side effects so it should not be pure-ugen.

- bus.lisp
- package.lisp
- sc.asd
- server.lisp
- ugen.lisp
This PR adds bus allocation similar to the buffer allocation already implemented. Manually specifying the bus number is no longer needed.
Use the `bus-audio` function to make a new audio bus, and `bus-control` to make a new control bus. Use `bus-free` to free a bus.
Additionally I made a few other minor changes:
- Added a `release` function to set the `gate` of a node to 0.
- Updated `floatfy` function to convert `nil` to 0 and `t` to 1.
- Fixed the `rate` function to return the highest rate from a list.
> Add bus allocation & handling; few other minor fixes

- README.md
- server.lisp
- synthdef.lisp
- ugens/compander.lisp
This PR includes 3 minor improvements:
- Remove a few references to `bye` and replace them with `free`. Also forward `bye` to `free` to avoid code duplication, and give a warning when `bye` is used.
- Fix arguments of `compander-d` to match the arguments of `compander`
- Fix `convert-code` to avoid converting the names of local bindings in `let` or `let*`:
Example, before:
```lisp
(sc::convert-code '(let ((mod (mod (lf-saw.ar 3 0 3) 1)))
mod))
;=> (LET ((SC::MOD~ (SC::MOD~ (LF-SAW.AR 3 0 3) 1)))
;  SC::MOD~)
```
Example, after:
```lisp
(sc::convert-code '(let ((mod (mod (lf-saw.ar 3 0 3) 1)))
mod))
;=> (LET ((MOD (SC::MOD~ (LF-SAW.AR 3 0 3) 1)))
;  MOD)
```
> 3 minor improvements

- buffer.lisp
- package.lisp
Simple addition of the buffer-read-channel function, which is useful if you want to load a mono file as a stereo buffer, for example.
> add support for #'buffer-read-channel

- README.md
- buffer.lisp
- bus.lisp
- package.lisp
- server.lisp
- synthdef.lisp
- ugen.lisp
This PR has a few relatively minor changes:
- add and export `buffer-dur` convenience method to get the duration of a buffer in seconds.
- add and export `bus-string` convenience method to get a string that scsynth can use to map a node's parameter to a bus.
- alllow `:to`, `:pos`, and `:id` to be specified as arguments to `synth` as per #34.
- export `get-synthdef-metadata`
- minor changes to `print-object` for several classes to print objects in a more standard way, i.e. using the class symbol so it's always printed with the correct package name or none if current package.
- a few minor docstring/documentation additions/fixes
- add and export `map-bus` function to map a bus to the argument of a node.
I'm also planning on improving `ctrl` in the future so that it will automatically map …
> several changes

- sc.asd
- ugens/testugens.lisp
This PR adds the `CheckBadValues` and `Sanitize` UGens. Sanitize was added to SuperCollider in 3.9.0.
> add testugens (including CheckBadValues and Sanitize UGens)

- server.lisp
As pointed out in #41, the initial bus allocation has an off-by-one error and allocates too many buses. Changing `:upto` to `:below` in the `loop`s fixes this.
> fix the initial bus allocation's off-by-one error - fixes #41.

- package.lisp
- ugens/envgen.lisp
This pull request implements an equivalent method to Supercollider's [Env.asSignal](http://doc.sccode.org/Classes/Env.html#-asSignal). This is useful for the client-side creation and manipulation of piecewise curves, made easy through the Envelope class. The curves can then be sent to a buffer for waveshaping or wavetable lookup synthesis, among other creative uses - see issue #44.
Additionally this PR also adds the 'hold' envelope shape, introduced in SC some versions ago.
> Envelope as signal; 'hold' shape

- README.md
- cl-collider.asd
- synthdef.lisp
- ugens/extras/ladspa.lisp
Here are the changes in this PR:
- add ladspa UGen (from sc3-plugins)
- fix `destructuring-bind` handling in `convert-code`
- fix `get-synthdef-metadata` so it returns information correctly when its argument is a node
- add cl-patterns contrib link. cl-patterns is my sequencing/patterns library that supports using cl-collider as its audio backend.
> add ladspa ugen + few other changes

- cl-collider.asd
- ugens/stochastic.lisp
This pull request adds defugens for dynamic stochastic synthesis generators UGens. `gendy1` through `gendy3` are on the default class library. `gendy4` and `gendy5` are extensions, but they are included here nonetheless.
> Add Gendy UGens.

- buffer.lisp
- package.lisp
This is the equivalent of sclang's `loadToFloatArray`. See related discussion in #38.
> Add function to get values from a buffer using a temporary file.

- buffer.lisp
- package.lisp
- util.lisp
This PR adds functions to load files in SuperCollider's wavetable format. It also includes some utility functions to resample lists to the correct length (since SC can only use buffers whose length is a power of two as wavetables).
> add functionality to load files in wavetable format

- server.lisp
By default, SuperCollider installs in a directory whose name contains the version number, e.g. "C:\Program Files\SuperCollider-3.10.0\". If the variables for the default paths in cl-collider point to a directory with the latest version number, users with other versions have to manually set them. Also when new versions of SuperCollider come out and are installed, changes have to be made.
To avoid this, this PR adds an automatic search for the SuperCollider directory in %ProgramFiles%.
> Improve default paths in Windows

- buffer.lisp
- cl-collider.asd
- operators.lisp
- server.lisp
- ugens/extras/mcldbufferugens.lisp
- ugens/ienvgen.lisp
This PR fixes `i-env-gen`. `IEnvGen` uses a different format than `EnvGen` does, so a new function had to be written for it.
Additionally, loading a file as a wavetable now preserves the path of the file loaded in the buffer metadata.
I also modified `flop` to use `nth-wrap` instead of rewriting it in a `labels`.
> fix i-env-gen + other minor changes

- server-options.lisp
- server.lisp
The scsynth binary is searched in system path, so this should work in all distros and all ways of installation.
For the plugin dirs there is larger set of possible locations that now covers default Makefile and default of debian based distros. Locations of other distros can be easily added in the future. Only locations that actually exist are used.
> enhance *sc-synth-program* and *sc-plugin-path* detection on linux

- package.lisp
- synthdef.lisp
a few minor changes:
- export `synthdef-metadata` (and `(setf synthdef-metadata)`)
- add a method for `swank` so that emacs will show the synth's argument list for the `synth` function
> synthdef-metadata + slime/swank arglist method

- server-options.lisp
Fixes #71 without removing functionality (no reverting), makes cl-collider play with the default system input and output device by default.
> Make server-options nilable/optional and device nil by default

- package.lisp
- ugens/fft.lisp
Call `sqrt~` instead of `sqrt` and export `running-sum-rms`.
> Fix `running-sum-rms` and export it

- ugens/filter.lisp
Call `sqrt~` instead of `sqrt` to allow the passing of a modulation
UGen, and not only a number, to the argument `rq`.
> Fix UGen definitions for some BEQSuite filters

- buffer.lisp
- util.lisp
This change uses `elt` instead of `nth` in `nth-wrap` and `blend-nth` in order to allow them to be used for any type of sequence.
It also coerces the resampled list to a vector when loading a sound as a wavetable. This greatly increases the speed of the `list-in-wavetable-format` function.
> Optimize wavetable conversion

- buffer.lisp
- server.lisp
This just makes `free` into a generic function, so it can be used on buffers, nodes, and possibly other objects in the future.
> make `free` a generic function

- package.lisp
This PR exports (buffer) `path` and (server) `boot-p`. Also removes unused symbols from the exported list in the package definition.
> Export symbols and cleanup package

- cl-collider.asd
- swank-extensions.lisp
- synthdef.lisp
- util.lisp
The library fails to load without Swank if had previously been compiled with it. My use of `#+swank` for this functionality was incorrect. Loading the functionality from a separate file via an `eval-when` instead fixes this issue.
This issue was originally reported for my own library at https://github.com/defaultxr/cl-patterns/issues/7 .
> conditionally load swank extensions

- buffer.lisp
- package.lisp
Scsynth has three routines to fill a buffer with sine waves: sine1 (only amplitudes for each partial), sine2 (also specifying frequency partials) and sine3 (also specifying frequency partials and phases). The function `wavetable` currently only accesses the first one. This PR adds the other two, abstracting away the particular method used to communicate to the server.
The name of the function is also changed to `buffer-fill`. This mechanism can be used beyond wavetable synthesis, and the data can in fact be created in wavetable format or not. I think `buffer-fill` is more descriptive, but I'd be glad to amend if you feel otherwise.
> Add buffer fill methods, change `wavetable` to `buffer-fill`

- cl-collider.asd
- server.lisp
- ugen.lisp
This sets the docstrings of the functions corresponding to the various UGens, according to their description on the helpfiles installed together with SuperCollider (if one such file exists).
The helpfiles come written in [SCDoc Syntax](http://doc.sccode.org/Reference/SCDocSyntax.html). Most features are ignored, other than finding the appropriate section and removing markup tags.
I only tested the code to find the correct documentation directory in Windows. It should also work in MacOS and Linux... testing on these systems would be appreciated!
> Add docstrings for UGens

- cl-collider.asd
- slynk-extensions.lisp
- util.lisp
This provides the same extensions for [sly/slynk](https://github.com/joaotavora/sly) as were already provided for `swank`.
> provide the swank extensions for slynk as well

- buffer.lisp
- package.lisp
This change fixes a bug in my previous implementation of `buffer-get-to-list`; it incorrectly limited the maximum number of frames to `(frames buffer)` rather than `(* (chanls buffer) (frames buffer))`.
Additionally, it introduces `buffer-to-list` which forwards to `buffer-load-to-list` by default, or to `buffer-get-to-list` if `buffer-load-to-list` is not available (i.e. non-local server).
It also introduces `buffer-get-to-array`, `buffer-load-to-array` and `buffer-to-array` which are similar to `buffer-get-to-list`, `buffer-load-to-list` and `buffer-to-list`, respectively, except that they return a (possibly multidimensional) array of the buffer's channels, rather than simply a flat list of the interlaced frame data.
i.e. for a 2-channel buffer `*buf*`:
```lisp
;; one channel, …
```
> better buffer-get-*, + buffer-to-list and buffer-to-array functions

- buffer.lisp
- util.lisp
This fixes a bug in `buffer-read-as-wavetable` if the user attempts to read a file bigger than 65536 frames as a wavetable. 65536 is SuperCollider's maximum supported buffer size for the `Osc` UGen so this change limits wavetables to that size.
Additionally, I also optimized the code of that function to make it run quite a bit faster by using vectors instead of lists in some places.
`linear-resample` also supports vectors as well now rather than only lists.
> bugfix and optimization of buffer-read-as-wavetable

- synthdef.lisp
- ugens/SC3plugins/DEINDUGens.lisp
- util.lisp
This PR includes the `JPverb` UGen, simplification of `full-pathname`, and the ability to use `synth` inside synthdefs.
Example:
```lisp
(defsynth :mdapiano ((gate 1) (freq 440) (vel 100) (random 0.1) (rel 0.9) (stereo 0.3) (amp 0.5))
(let* ((sig (/ (mda-piano.ar freq :gate gate :vel vel :release rel :stereo stereo :random random :sustain 0) 2))
(ds (detect-silence.ar sig 1.0e-4 :act :free)))
(declare (ignore ds))
(out.ar 0 (* sig amp))))
(defsynth :tremolo-piano ((gate 1) (freq 440) (amp 0.5))
(out.ar 0 (* (sin-osc.ar 8 0 0.5 0.5)
(synth :mdapiano :gate gate :freq freq)
amp)))
```
Caveats(?):
- The `synth` form will not automatically grab the values of its arguments from the synthdef; they have to be specified. This is similar to how regular function calls work though so it is probably …
> Allow use of `synth` inside synthdefs + JPverb

- ugen.lisp
Remove unnecessary conditions from the regex, that might prevent correct parsing.
> Fix ugen documentation builder

- buffer.lisp
- server.lisp
- ugens/EnvGen.lisp
Hi,
3 minor improvements/fixes:
- Better error messages when the user attempts to make an invalid `env`
- Fix `buffer-get-to-array`
- Record the server samplerate from `/status.reply`
> Improve `env` error messages, fix `buffer-get-to-array`, record server samplerate from `/status.reply`

- synthdef.lisp
This fixes the following error:
```
SC-USER> (defsynth test ())
#<CL-COLLIDER::SYNTHDEF :name "test">
SC-USER> (synth 'test :pos :tail)
---> Can't floatify :TAIL
```
or
```
SC-USER> (defparameter *aux-group* (make-group))
*AUX-GROUP*
SC-USER> (synth 'test :to *aux-group*)
---> Can't floatify #<CL-COLLIDER::GROUP :server #<CL-COLLIDER::EXTERNAL-SERVER localhost-127.0.0.1:4444> :id 3>
```
This was a bug introduced [here](https://github.com/byulparan/cl-collider/commit/03ace5af8d4ce62e857a24ccf2c74f81999037aa).
> Fix errors when calling `synth' with :pos or :to keywords.

- slynk-extensions.lisp
- swank-extensions.lisp
- synthdef.lisp
Document the `ID`, `POS` and `TO` keyword arguments for `synth`. Also make them show up in sly and slime. Should not change usage.
> Documentation for `synth`'s arguments.

- package.lisp
- server.lisp
Implement `group-free-all` as a function that frees all nodes in a group without freeing that group.
Rename the existing `group-free-all` to `free-all`, to better reflect what it does and allow for consistency with sc.
If the latter is too much of a breaking change, I'd be happy to reverse it and give the new function another name. Maybe `free-in-group`?
> implement sc's Group.freeAll

- server.lisp
Add a method to `floatfy` for envelope shape name symbols (i.e. `:lin`, `:exp`, etc). This should avoid the error described in #145.
I also added a method to floatfy lists by floatfying each element of the list. This allows users to provide a list of env shapes as well.
> `floatfy` env shape symbols
